// Code generated by protoc-gen-go. DO NOT EDIT.
// source: EduData.proto

package protoTest

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EduData_SubjectType int32

const (
	EduData_KOREAN   EduData_SubjectType = 0
	EduData_ENGLISH  EduData_SubjectType = 1
	EduData_HISTORY  EduData_SubjectType = 2
	EduData_COMPUTER EduData_SubjectType = 3
	EduData_ETC      EduData_SubjectType = 4
)

var EduData_SubjectType_name = map[int32]string{
	0: "KOREAN",
	1: "ENGLISH",
	2: "HISTORY",
	3: "COMPUTER",
	4: "ETC",
}

var EduData_SubjectType_value = map[string]int32{
	"KOREAN":   0,
	"ENGLISH":  1,
	"HISTORY":  2,
	"COMPUTER": 3,
	"ETC":      4,
}

func (x EduData_SubjectType) String() string {
	return proto.EnumName(EduData_SubjectType_name, int32(x))
}

func (EduData_SubjectType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_59dbc371a62aefe6, []int{0, 0}
}

type EduData struct {
	Name                 string             `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   string             `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Email                string             `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Subjects             []*EduData_Subject `protobuf:"bytes,4,rep,name=subjects,proto3" json:"subjects,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *EduData) Reset()         { *m = EduData{} }
func (m *EduData) String() string { return proto.CompactTextString(m) }
func (*EduData) ProtoMessage()    {}
func (*EduData) Descriptor() ([]byte, []int) {
	return fileDescriptor_59dbc371a62aefe6, []int{0}
}

func (m *EduData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EduData.Unmarshal(m, b)
}
func (m *EduData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EduData.Marshal(b, m, deterministic)
}
func (m *EduData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EduData.Merge(m, src)
}
func (m *EduData) XXX_Size() int {
	return xxx_messageInfo_EduData.Size(m)
}
func (m *EduData) XXX_DiscardUnknown() {
	xxx_messageInfo_EduData.DiscardUnknown(m)
}

var xxx_messageInfo_EduData proto.InternalMessageInfo

func (m *EduData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EduData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *EduData) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *EduData) GetSubjects() []*EduData_Subject {
	if m != nil {
		return m.Subjects
	}
	return nil
}

type EduData_Subject struct {
	SubjectName          string              `protobuf:"bytes,1,opt,name=SubjectName,proto3" json:"SubjectName,omitempty"`
	SubjectRank          string              `protobuf:"bytes,2,opt,name=SubjectRank,proto3" json:"SubjectRank,omitempty"`
	Type                 EduData_SubjectType `protobuf:"varint,3,opt,name=type,proto3,enum=protoTest.EduData_SubjectType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *EduData_Subject) Reset()         { *m = EduData_Subject{} }
func (m *EduData_Subject) String() string { return proto.CompactTextString(m) }
func (*EduData_Subject) ProtoMessage()    {}
func (*EduData_Subject) Descriptor() ([]byte, []int) {
	return fileDescriptor_59dbc371a62aefe6, []int{0, 0}
}

func (m *EduData_Subject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EduData_Subject.Unmarshal(m, b)
}
func (m *EduData_Subject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EduData_Subject.Marshal(b, m, deterministic)
}
func (m *EduData_Subject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EduData_Subject.Merge(m, src)
}
func (m *EduData_Subject) XXX_Size() int {
	return xxx_messageInfo_EduData_Subject.Size(m)
}
func (m *EduData_Subject) XXX_DiscardUnknown() {
	xxx_messageInfo_EduData_Subject.DiscardUnknown(m)
}

var xxx_messageInfo_EduData_Subject proto.InternalMessageInfo

func (m *EduData_Subject) GetSubjectName() string {
	if m != nil {
		return m.SubjectName
	}
	return ""
}

func (m *EduData_Subject) GetSubjectRank() string {
	if m != nil {
		return m.SubjectRank
	}
	return ""
}

func (m *EduData_Subject) GetType() EduData_SubjectType {
	if m != nil {
		return m.Type
	}
	return EduData_KOREAN
}

// Our address book file is just one of these.
type EduHistory struct {
	Data                 []*EduData `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *EduHistory) Reset()         { *m = EduHistory{} }
func (m *EduHistory) String() string { return proto.CompactTextString(m) }
func (*EduHistory) ProtoMessage()    {}
func (*EduHistory) Descriptor() ([]byte, []int) {
	return fileDescriptor_59dbc371a62aefe6, []int{1}
}

func (m *EduHistory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EduHistory.Unmarshal(m, b)
}
func (m *EduHistory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EduHistory.Marshal(b, m, deterministic)
}
func (m *EduHistory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EduHistory.Merge(m, src)
}
func (m *EduHistory) XXX_Size() int {
	return xxx_messageInfo_EduHistory.Size(m)
}
func (m *EduHistory) XXX_DiscardUnknown() {
	xxx_messageInfo_EduHistory.DiscardUnknown(m)
}

var xxx_messageInfo_EduHistory proto.InternalMessageInfo

func (m *EduHistory) GetData() []*EduData {
	if m != nil {
		return m.Data
	}
	return nil
}

type Reply struct {
	Count                int32    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Reply) Reset()         { *m = Reply{} }
func (m *Reply) String() string { return proto.CompactTextString(m) }
func (*Reply) ProtoMessage()    {}
func (*Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_59dbc371a62aefe6, []int{2}
}

func (m *Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reply.Unmarshal(m, b)
}
func (m *Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reply.Marshal(b, m, deterministic)
}
func (m *Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reply.Merge(m, src)
}
func (m *Reply) XXX_Size() int {
	return xxx_messageInfo_Reply.Size(m)
}
func (m *Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_Reply.DiscardUnknown(m)
}

var xxx_messageInfo_Reply proto.InternalMessageInfo

func (m *Reply) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func init() {
	proto.RegisterEnum("protoTest.EduData_SubjectType", EduData_SubjectType_name, EduData_SubjectType_value)
	proto.RegisterType((*EduData)(nil), "protoTest.EduData")
	proto.RegisterType((*EduData_Subject)(nil), "protoTest.EduData.Subject")
	proto.RegisterType((*EduHistory)(nil), "protoTest.EduHistory")
	proto.RegisterType((*Reply)(nil), "protoTest.reply")
}

func init() { proto.RegisterFile("EduData.proto", fileDescriptor_59dbc371a62aefe6) }

var fileDescriptor_59dbc371a62aefe6 = []byte{
	// 317 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x4d, 0x4f, 0xbb, 0x40,
	0x10, 0xc6, 0xff, 0xbc, 0xb4, 0xdb, 0x4e, 0xff, 0x36, 0x64, 0xe2, 0x81, 0x34, 0xd1, 0x34, 0x1c,
	0x4c, 0x4f, 0x4d, 0x44, 0xe3, 0xc9, 0x8b, 0xa9, 0x1b, 0x5b, 0x5f, 0x8a, 0x59, 0xf0, 0xe0, 0x71,
	0x5b, 0xf6, 0x80, 0xb6, 0x40, 0x60, 0x39, 0x70, 0xf4, 0xf3, 0xf9, 0xa5, 0x0c, 0x0b, 0x22, 0x89,
	0xf5, 0xc4, 0x3c, 0xbf, 0x79, 0x32, 0xf3, 0x30, 0x0b, 0x47, 0x34, 0x2c, 0x6e, 0xb9, 0xe4, 0xf3,
	0x34, 0x4b, 0x64, 0x82, 0x43, 0xf5, 0x09, 0x44, 0x2e, 0x9d, 0x4f, 0x1d, 0x48, 0xd3, 0x44, 0x04,
	0x33, 0xe6, 0x7b, 0x61, 0x6b, 0x53, 0x6d, 0x36, 0x64, 0xaa, 0xc6, 0x31, 0xe8, 0x51, 0x68, 0xeb,
	0x8a, 0xe8, 0x51, 0x88, 0xc7, 0xd0, 0x13, 0x7b, 0x1e, 0xed, 0x6c, 0x43, 0xa1, 0x5a, 0xe0, 0x15,
	0x0c, 0xf2, 0x62, 0xf3, 0x26, 0xb6, 0x32, 0xb7, 0xcd, 0xa9, 0x31, 0x1b, 0xb9, 0x93, 0x79, 0xbb,
	0x63, 0xfe, 0xbd, 0xdc, 0xaf, 0x2d, 0xac, 0xf5, 0x4e, 0x3e, 0x34, 0x20, 0x0d, 0xc5, 0x29, 0x8c,
	0x9a, 0x72, 0xfd, 0x13, 0xa2, 0x8b, 0x3a, 0x0e, 0xc6, 0xe3, 0xf7, 0x26, 0x54, 0x17, 0xa1, 0x0b,
	0xa6, 0x2c, 0x53, 0xa1, 0xc2, 0x8d, 0xdd, 0xd3, 0xbf, 0x33, 0x04, 0x65, 0x2a, 0x98, 0xf2, 0x3a,
	0xf7, 0xed, 0xd4, 0x0a, 0x22, 0x40, 0xff, 0xc1, 0x63, 0xf4, 0x66, 0x6d, 0xfd, 0xc3, 0x11, 0x10,
	0xba, 0xbe, 0x7b, 0x5c, 0xf9, 0x4b, 0x4b, 0xab, 0xc4, 0x72, 0xe5, 0x07, 0x1e, 0x7b, 0xb5, 0x74,
	0xfc, 0x0f, 0x83, 0x85, 0xf7, 0xf4, 0xfc, 0x12, 0x50, 0x66, 0x19, 0x48, 0xc0, 0xa0, 0xc1, 0xc2,
	0x32, 0x9d, 0x4b, 0x00, 0x1a, 0x16, 0xcb, 0x28, 0x97, 0x49, 0x56, 0xe2, 0x19, 0x98, 0x21, 0x97,
	0xdc, 0xd6, 0xd4, 0x45, 0xf0, 0x77, 0x1a, 0xa6, 0xfa, 0xce, 0x09, 0xf4, 0x32, 0x91, 0xee, 0xca,
	0xea, 0xb8, 0xdb, 0xa4, 0x88, 0xa5, 0xfa, 0xf9, 0x1e, 0xab, 0x85, 0x7b, 0x0d, 0xc4, 0x17, 0x52,
	0xbd, 0xd0, 0x39, 0x90, 0xbc, 0x29, 0x0f, 0x8c, 0x9b, 0x1c, 0x60, 0x9b, 0xbe, 0x42, 0x17, 0x5f,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x35, 0x4a, 0x4e, 0xae, 0x03, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SetDataClient is the client API for SetData service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SetDataClient interface {
	// rpc setSubject(EduData.Subject) returns (reply);
	SetData(ctx context.Context, in *EduData, opts ...grpc.CallOption) (*EduData, error)
}

type setDataClient struct {
	cc *grpc.ClientConn
}

func NewSetDataClient(cc *grpc.ClientConn) SetDataClient {
	return &setDataClient{cc}
}

func (c *setDataClient) SetData(ctx context.Context, in *EduData, opts ...grpc.CallOption) (*EduData, error) {
	out := new(EduData)
	err := c.cc.Invoke(ctx, "/protoTest.SetData/setData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SetDataServer is the server API for SetData service.
type SetDataServer interface {
	// rpc setSubject(EduData.Subject) returns (reply);
	SetData(context.Context, *EduData) (*EduData, error)
}

func RegisterSetDataServer(s *grpc.Server, srv SetDataServer) {
	s.RegisterService(&_SetData_serviceDesc, srv)
}

func _SetData_SetData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EduData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SetDataServer).SetData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protoTest.SetData/SetData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SetDataServer).SetData(ctx, req.(*EduData))
	}
	return interceptor(ctx, in, info, handler)
}

var _SetData_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protoTest.SetData",
	HandlerType: (*SetDataServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "setData",
			Handler:    _SetData_SetData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "EduData.proto",
}
